### ISSUE TITLE
Improve edit summary of QuickReport

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#221]
Instead of just "add report" it should be "add report for [[_Some page_]]" to make searching the history a little easier.

**Comment by kynikos** [comment]
As the edit summary is a configurable string, I've added support for `%t` which is substituted with a link to the reported article's title. To support future additional substitutions, `%` is in general a special character that is never rendered in the summary, unless preceded by another `%` (i.e. in order to render `%` it's now necessary to write `%%` in the configured string; to render `%t` literally it's necessary to write `%%t` and so on).

**Note** that your configuration can't be updated automatically, so you should change `add report` to `add report for %t` manually.

**Comment by lahwaacz** [comment]
Done, thanks.
