### ISSUE TITLE
Inconsistent font size in Vector style

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#229]
The `<fieldset id="WikiMonkey">` element is put inside `<div class="mw-body-content">` on the edit pages, but not e.g. on category pages where it's just inside `<div class="mw-body">`. The `mw-body-content` class has `font-size: 0.8em` in the Vector style, so WikiMonkey looks inconsistent on the category pages.

**Comment by kynikos** [comment]
Thank you, you've even gone to see why that was happening! :)

That (and something else) is fixed in 4.1.0, just released. By default the script will (should) ask you the permission to upgrade itself automatically it next Saturday. If you're impatient you can edit the version number in your common.js page manually, and I'd suggest you to use the new minified script too (easy copy-paste below):

    mw.loader.load('https://rawcdn.githack.com/kynikos/wiki-monkey/v4.1.0/dist/WikiMonkey-ArchWiki.min.js');

Alternatively you can start forcing the check for a new version to happen every day by adding the following `wikiMonkeyConfig` option just above Wiki Monkey's `mw.loader.load` line:
```
wikiMonkeyConfig = {update_check_wdays: [0, 1, 2, 3, 4, 5, 6]};
mw.loader.load('https://rawcdn.githack.com/kynikos/wiki-monkey/v4.0.0/dist/WikiMonkey-ArchWiki.js');
```
In this case you'd still have to edit the page manually if you wanted to start using the minified version though (I decided to not be intrusive and force the switch automatically) :
```
wikiMonkeyConfig = {update_check_wdays: [0, 1, 2, 3, 4, 5, 6]};
mw.loader.load('https://rawcdn.githack.com/kynikos/wiki-monkey/v4.1.0/dist/WikiMonkey-ArchWiki.min.js');
```
