### ISSUE TITLE
Section heading "shortcuts" not visible on protected pages

### ISSUE THREAD

**Issue by kattjevfel** [kynikos/wiki-monkey#250]
When viewing a protected page as a regular user makes none of the shortcuts show up next to section headings. I can understand the edit button being gone, but the rest are very useful still.

Problem:
![2021-05-24_17-05-01](https://user-images.githubusercontent.com/6226312/119367577-60d98200-bcb2-11eb-9291-e8c82ffa5577.png)

Example of them being visible:
![2021-05-24_17-06-42](https://user-images.githubusercontent.com/6226312/119367690-7f3f7d80-bcb2-11eb-872f-1ebe98917839.png)

**Comment by kynikos** [comment]
Yep, WM looks for `mw-editsection` class elements to inject those links, and clearly MediaWiki doesn't render them for users without edit rights on the page... I've got to find another reliable way to identify sections.

https://github.com/kynikos/wiki-monkey/blob/bcfef4fcdbbc8aced86490dd73ff6e9f9a1a6bf2/src/app/index.js#L85

**Comment by kattjevfel** [comment]
The update seems to have brought the side effect that translations of (English) pages I can't edit, also doesn't show the edit button.

![2021-05-29_01-15-54](https://user-images.githubusercontent.com/6226312/120049819-813f6e80-c01b-11eb-8101-ecfb6f368e41.png)
I have access to edit this page but the edit button is gone :p

**Comment by kynikos** [comment]
Most main pages have the `__NOEDITSECTION__` switch at the top, which hides edit buttons, I'm pretty sure "Main page (Svenska)" didn't have links even before, so the behaviour would be expected. Can you confirm that this only happens in pages with `__NOEDITSECTION__`?

**Comment by kattjevfel** [comment]
Oh, I guess that is it then, I just blindly copied the `__NOTOC__ __NOEDITSECTION__` when making my translation. But I'm 99% sure they were there before.

**Comment by kynikos** [comment]
Hmm if the links had been there before, it would mean that `__NOEDITSECTION__` wasn't working... Anyway, technically I could very easily add the edit buttons even when natively they'd be missing from the page because of `__NOEDITSECTION__`, however 1) they'd also appear in pages where the user doesn't have edit privileges (unless I found another way to prevent that), and 2) it would practically become an override of `__NOEDITSECTION__`, while the proper way to make the links appear would actually be to simply remove that flag from the page.
